---
title: "About"
output:
  workflowr::wflow_html:
    toc: false
editor_options:
  chunk_output_type: console
---

DNA phenotyping is a challenging statistical problem, complicated by inference in unobservable archaic populations. The question of what our archaic hominin ancestors may have looked like has captured the attention of scientists and popular culture. Previous research has sequenced that pigmentation related variants in ancient and archaic genomes, but this work remains spread across single locus studies and phenotype prediction attempts rather than directly consolidated into a systematic archaic focused resource. Here, I attempt to evaluate the possibility of phenotype prediction in 14 archaic Neanderthal and Denisovan individuals through the analysis of depth and missingness in available genomes, and compare available pigmentation-related SNPs in these archaic populations to diverse modern human genomes obtained from the Simons Genome Diversity Project. PCAs were constructed using the modern human genomes, and archaic samples were then projected onto the PC space. Sequencing depth (including regions where depth = 0) of the archaic samples was calculated using Samtools. Analyses of depth and missingness were performed as a mixed effects logistic regression of missingness and two simulations of consensus base call confidence conferred by sequence depth. There is significant variation in coverage and depth across archaic samples, for which age and structural influences are significant predictors. Archaic samples cluster near Eurasians in a genome-wide SNP panel, but with Africans in a pigmentation panel. 
