```{r setup, include = FALSE, message = FALSE, warning = FALSE}
library(data.table)
library(stringr)
library(tidyverse)
library(readr)
library(dplyr)
```

# Cleaning EBI SNP list

```{r cleaning}
snps_set <- read.csv("/Users/lilyheald/Documents/GitHub/PAINT/data/skin_pigmentation.tsv", sep = "\t")

snps_set <- snps_set %>%
  mutate(
    riskAllele = str_trim(riskAllele),
    riskAllele = if_else(
      str_detect(riskAllele, "^rs\\d+"),
      str_extract(riskAllele, "^rs\\d+"),
      NA_character_
    )
  ) %>%
  filter(!is.na(riskAllele))

write.csv(snps_set, file = "/Users/lilyheald/Documents/GitHub/PAINT/data/pigmentation_snps.csv", row.names = FALSE)
```


```{r simons_meta}
simons_sample <- read_csv("/Users/lilyheald/Documents/GitHub/PAINT/data/simons_metadata.csv",
                          show_col_types = FALSE)
simons_whole <- read_csv("/Users/lilyheald/Documents/GitHub/PAINT/data/simons_whole.csv",
                         show_col_types = FALSE)
simons_whole <- simons_whole %>%
  group_by(sample_id) %>%
  slice(1) %>%
  ungroup()

head(simons_sample)

sample_metadata <- merge(simons_sample, simons_whole, by.x = "Sample_ID", by.y = "sample_id")
sample_metadata
write.csv(sample_metadata, file = "/Users/lilyheald/Documents/GitHub/PAINT/data/modern_metadata.csv", row.names = FALSE)
```







