---
title: "Distribution of Variation in Pigmentation-Related SNPs in the Hominin Lineage"
author: "Lily Heald"
date: "`r Sys.Date()`"
output:
  workflowr::wflow_html:
    toc: true  
    toc_depth: 2 
    code_folding: hide  
site: workflowr::wflow_site
---

# Project Overview

Current scholarship on pigmentation in ancient and archaic humans is disproportionately centered on the study of introgressed archaic alleles in modern human populations rather than on cataloging the pigment-related variants directly in the genomes of archaic individuals (Dannemann et al., 2017a; Kang et al., 2023; McArthur et al., 2020). As a result, understanding of pigmentation genetics remains dispersed across party overlapping literature including selection studies, phenotype inference, and selection-based analyses. This has resulted in a fragmented understanding of the genetic architecture underlying pigmentation in ancient and archaic hominins. 

Existing work has shown that pigmentation related variants in ancient and archaic genomes can be directly analysed, but the evidence remains spread across single locus studies and phenotype prediction attempts rather than directly consolidated into a systematic archaic focused resource (Brand et al., 2022; Cerqueira et al., 2012; Ferrando-Bernal et al., 2025; Lalueza-Fox et al., 2007a; Perry et al., 2015). Direct discussion of pigmentation-related variation in archaic genomes has often centered around a small number of loci. In particular, the discussion of pigmentation-related alleles is largely limited to MC1R, with studies focusing on the introgression of archaic haplotypes into modern human populations (Ding et al., 2014; Lalueza-Fox et al., 2007a). Selection-based approaches in modern and ancient human populations have successfully identified key loci associated with pigmentation; however, these studies typically infer selection dynamics without comparing archaic genotypes (Ju & Mathieson, 2021a). Genome-wide analyses of archaic introgression have identified regulatory and trait-associated effects relevant to skin and hair pigmentation, but these studies do not provide locus-level catalogs for variants associated with the pigmentation of keratinized tissues in archaic genomes (Dannemann et al., 2017b; Kang et al., 2023; Rinker et al., 2019; Witt et al., 2022). In addition, earlier multi-locus approaches used smaller marker panels, whereas the present study examines a larger set of 395 pigmentation related SNPs, allowing broader locus coverage (Cerqueira et al., 2012). 

The literature suggests a gap between functional or evolutionary inference in archaic genomes and descriptive genomic characterization. No study has yet curated a single, comprehensive locus-level inventory of pigmentation-associated variants in archaic genomes with explicit comparison to diverse modern human genomes. The primary aim of this project is to provide a comprehensive locus catalog for variants associated with the pigmentation of keratinized tissues and to analyze the distribution and frequency of these variants across available archaic genomes. This analysis will be conducted in comparison to a diverse sample of modern human genomes to assess patterns of shared variation, divergence, and potential introgression. By shifting focus from inference based on modern populations to direct characterization of archaic genomic data, this study seeks to refine current models of pigmentation evolution and its underlying genetic architecture. 

# Key Results
Background on the samples analyzed is available on the **Introduction** analysis page:
- [View UV map and aDNA sites](introduction.html)

Population genetics analyses are available on the **Analysis** page:
- [View genetic PCAs](analysis.html)

# Data Sources
- NASA Earth Observations: [AURA_UVI_CLIM_M](https://neo.gsfc.nasa.gov/view.php?datasetId=AURA_UVI_CLIM_M)
- NHGRI-EBI Catalog of GWAS associated pigmentation variants: [NHGRI-EBI](https://www.ebi.ac.uk/gwas/efotraits/OBA_VT0002095)
- Simons Genome Diversity Project: [SGDP](https://www.simonsfoundation.org/simons-genome-diversity-project/)
- Max-Plank Institute neanderthal genomes: [MPI-EVA](http://ftp.eva.mpg.de/neandertal/)



