---
title: "PCA"
output: html_document
---

# SGDP whole-genome SNP panel

```{r setup, echo = FALSE, message = FALSE, warning = FALSE}
library(data.table)
library(dplyr)
library(ggplot2)
library(wesanderson)
library(showtext)
library(workflowr)
library(patchwork)

font_add_google("Lato", "lato")
showtext_auto()

pca_pal <- c(
  "Neanderthal" = "#E6A0C4",  
  "Denisovan"   =  "#7294D4",
  "Hybrid"      = "#CEC1EA",
  "CentralAsiaSiberia" =  "#5BBCD6",
  "EastAsia" = "#00A08A",
  "Africa" = "#FF0000",
  "Oceania" = "#F2AD00",
  "WestEurasia" = "#F98400"   
)
```

```{r paths, echo = FALSE, message = FALSE, warning = FALSE}
modern_file <- "data/sgdp.wg.pca.eigenvec"
ancient_file <- "data/ancient.projected.sgdp.sscore"
metadata_file <- "data/modern_metadata.csv"
```

```{r process, echo = FALSE, message = FALSE, warning = FALSE}
modern <- fread(modern_file, header = TRUE)
colnames(modern) <- c("IID", paste0("PC", 1:10))
metadata <- fread(metadata_file)

modern <- modern %>%
  left_join(metadata, by = c("IID"="library_id")) %>%
  mutate(Type = "Modern")

# ancient projections
ancient <- fread(ancient_file)

ancient_pcs <- ancient %>%
  select(IID, starts_with("PC")) %>%
  mutate(Type = "Ancient")

ancient_pcs <- ancient_pcs %>%
  mutate(
    Group = case_when(
      IID %in% c("Denisova3", "Denisova25") ~ "Denisovan",
      IID %in% c("Denisova11") ~ "Hybrid",
      TRUE ~ "Neanderthal"
    )
  )

modern_clean <- modern %>%
  select(IID, starts_with("PC"), Population_ID, Region) %>%
  mutate(Type = "Modern",
         Group = Population_ID)

ancient_clean <- ancient_pcs %>%
  rename_with(
    ~ gsub("_AVG", "", .x),
    starts_with("PC")
  ) %>%
  select(IID, Group, starts_with("PC")) %>%
  mutate(
    Population_ID = "Ancient",
    Region = Group,
    Type = "Ancient"
  )

df <- bind_rows(modern_clean, ancient_clean)
```

```{r plot, echo = FALSE, message = FALSE, warning = FALSE, fig.width=9, fig.height=3}
df$labels <- df$Group
df[20:30, ]$labels <- NA
df[19, ]$labels <- NA

x1 <- ggplot(df, aes(PC1, PC2)) +
  geom_point(
    aes(color = Region, shape = Type),
    size = 3,
    alpha = 0.8
  ) +
  geom_text(aes(label = labels), 
            position = position_jitter(width = 0.05, height = 0.05), 
            size = 2.5) + 
  scale_color_manual(values = pca_pal) +
  theme_minimal(base_family = "lato", base_size = 14) +
  labs(
    x = "PC1",
    y = "PC2",
    color = "Population"
  ) +
  theme(
    legend.position = "right",
    panel.grid = element_blank()
  )

y1 <- ggplot(df, aes(PC3, PC4)) +
  geom_point(
    aes(color = Region, shape = Type),
    size = 3,
    alpha = 0.8
  ) +
  geom_text(aes(label = labels), 
            position = position_jitter(width = 0.05, height = 0.05), 
            size = 2.5) +  
  scale_color_manual(values = pca_pal) +
  theme_minimal(base_family = "lato", base_size = 14) +
  labs(
    x = "PC3",
    y = "PC4",
    color = "Population"
  ) +
  theme(
    legend.position = "right",
    panel.grid = element_blank()
  )

combined_plot <- (x1 | y1) + 
  plot_layout(guides = 'collect') + 
  plot_annotation(title = 'PCA of SGDP SNP panel', theme = theme(plot.title = element_text(hjust = 0.5)))

combined_plot
```


# Pigmentation subset

```{r processing2, echo = FALSE, message = FALSE, warning = FALSE}
modern_file <- "data/pigmentation.pca.eigenvec"
ancient_file <- "data/ancient.projected.pig.sscore"
metadata_file <- "data/modern_metadata.csv"

modern <- fread(modern_file, header = TRUE)
colnames(modern) <- c("IID", paste0("PC", 1:10))

metadata <- fread(metadata_file)

modern <- modern %>%
  left_join(metadata, by = c("IID" = "library_id")) %>%
  mutate(
    Type = "Modern",
    Group = Population_ID
  )

ancient <- fread(ancient_file)

ancient_pcs <- ancient %>%
  select(IID, starts_with("PC")) %>%
  rename_with(~ gsub("_AVG", "", .x), starts_with("PC")) %>%
  mutate(Type = "Ancient")

ancient_pcs <- ancient_pcs %>%
  mutate(
    Group = case_when(
      IID %in% c("Denisova3", "Denisova25") ~ "Denisovan",
      IID %in% c("Denisova11") ~ "Hybrid",
      TRUE ~ "Neanderthal"
    ),
    Region = "Ancient"
  )

modern_clean <- modern %>%
  select(IID, starts_with("PC"), Population_ID, Region, Group, Type)

ancient_clean <- ancient_pcs %>%
  select(IID, starts_with("PC"), Group, Region, Type) %>%
  mutate(Population_ID = "Ancient",
         Region = Group)

df <- bind_rows(modern_clean, ancient_clean)
```

```{r plot2, echo = FALSE, message = FALSE, warning = FALSE, fig.width=9, fig.height=3}
df$labels <- df$Group
df[20:30, ]$labels <- NA
df[19, ]$labels <- NA

x2 <- ggplot(df, aes(PC1, PC2))+
  geom_point(
    aes(color = Region, shape = Type),
    size = 3,
    alpha = 0.8
  ) +
  geom_text(aes(label = labels), 
            position = position_jitter(width = 0.05, height = 0.05), 
            size = 2.5) +  
  scale_color_manual(values = pca_pal) +
  theme_minimal(base_family = "lato", base_size = 14) +
  labs(
    x = "PC1",
    y = "PC2",
    color = "Population"
  ) +
  theme(
    legend.position = "right",
    panel.grid = element_blank()
  )
y2 <- ggplot(df, aes(PC3, PC4))+
  geom_point(
    aes(color = Region, shape = Type),
    size = 3,
    alpha = 0.8
  ) +
  geom_text(aes(label = labels), 
            position = position_jitter(width = 0.05, height = 0.05), 
            size = 2.5) + 
  scale_color_manual(values = pca_pal) +
  theme_minimal(base_family = "lato", base_size = 14) +
  labs(
    x = "PC3",
    y = "PC4",
    color = "Population"
  ) +
  theme(
    legend.position = "right",
    panel.grid = element_blank()
  )
combined_plot <- (x2 | y2) + 
  plot_layout(guides = 'collect') + 
  plot_annotation(title = 'PCA of pigmentation SNP panel', theme = theme(plot.title = element_text(hjust = 0.5)))

combined_plot
```



